import {icons} from "@/constansts/icon";

export const tabs: AppTab[] = [
    {name: "index", title: "Home", icon: icons.home},
    {name: "subscriptions", title: "Subscriptions", icon: icons.wallet},
    {name: "insights", title: "Insights", icon: icons.activity},
    {name: "settings", title: "Settings", icon: icons.setting},
];

export const HOME_USER = {
    name: "Joan",
};

export const HOME_BALANCE = {
    amount: 2489.48,
    nextRenewalDate: "2026-03-18T09:00:00.000Z",
};

export const UPCOMING_SUBSCRIPTIONS: UpcomingSubscription[] = [
    {
        id: "spotify",
        icon: icons.spotify,
        name: "Spotify",
        price: 5.99,
        currency: "USD",
        daysLeft: 2,
    },
    {
        id: "notion",
        icon: icons.notion,
        name: "Notion",
        price: 12.0,
        currency: "USD",
        daysLeft: 4,
    },
    {
        id: "figma",
        icon: icons.figma,
        name: "Figma",
        price: 15.0,
        currency: "USD",
        daysLeft: 6,
    },
];

export const HOME_SUBSCRIPTIONS: Subscription[] = [
    {
        id: "adobe-creative-cloud",
        icon: icons.adobe,
        name: "Adobe Creative Cloud",
        plan: "Teams Plan",
        category: "Design",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2025-03-20T10:00:00.000Z",
        price: 77.49,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-20T10:00:00.000Z",
        color: "#f5c542",
    },
    {
        id: "github-pro",
        icon: icons.github,
        name: "GitHub Pro",
        plan: "Developer",
        category: "Developer Tools",
        paymentMethod: "Mastercard ending in 2408",
        status: "active",
        startDate: "2024-11-24T10:00:00.000Z",
        price: 9.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-24T10:00:00.000Z",
        color: "#e8def8",
    },
    {
        id: "claude-pro",
        icon: icons.claude,
        name: "Claude Pro",
        plan: "Pro Plan",
        category: "AI Tools",
        paymentMethod: "Amex ending in 1010",
        status: "paused",
        startDate: "2025-06-27T10:00:00.000Z",
        price: 20.0,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-27T10:00:00.000Z",
        color: "#b8d4e3",
    },
    {
        id: "canva-pro",
        icon: icons.canva,
        name: "Canva Pro",
        plan: "Yearly Access",
        category: "Design",
        paymentMethod: "Visa ending in 7784",
        status: "cancelled",
        startDate: "2024-04-02T10:00:00.000Z",
        price: 119.99,
        currency: "USD",
        billing: "Yearly",
        renewalDate: "2026-04-02T10:00:00.000Z",
        color: "#b8e8d0",
    },
];

export const SUBSCRIPTIONS: Subscription[] = [
    {
        id: "adobe-creative-cloud",
        icon: icons.adobe,
        name: "Adobe Creative Cloud",
        plan: "Premium",
        category: "Design",
        paymentMethod: "Visa ending in 8530",
        status: "active",
        startDate: "2025-03-20T10:00:00.000Z",
        price: 77.49,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-20T10:00:00.000Z",
        color: "#f5c542",
    },

    {
        id: "spotify-student",
        icon: icons.spotify,
        name: "Spotify",
        plan: "Student",
        category: "Music",
        paymentMethod: "Mastercard ending in 1193",
        status: "active",
        startDate: "2025-02-02T10:00:00.000Z",
        price: 5.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-02-02T10:00:00.000Z",
        color: "#1DB954",
    },

    {
        id: "figma-pro",
        icon: icons.figma,
        name: "Figma",
        plan: "Professional",
        category: "Design",
        paymentMethod: "Visa ending in 4428",
        status: "active",
        startDate: "2025-04-15T10:00:00.000Z",
        price: 12,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-04-15T10:00:00.000Z",
        color: "#A259FF",
    },

    {
        id: "notion-plus",
        icon: icons.notion,
        name: "Notion",
        plan: "Plus",
        category: "Productivity",
        paymentMethod: "Visa ending in 9921",
        status: "active",
        startDate: "2025-05-01T10:00:00.000Z",
        price: 8,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-05-01T10:00:00.000Z",
        color: "#000000",
    },

    {
        id: "github-copilot",
        icon: icons.github,
        name: "GitHub Copilot",
        plan: "Individual",
        category: "Developer Tools",
        paymentMethod: "Visa ending in 3845",
        status: "active",
        startDate: "2025-01-18T10:00:00.000Z",
        price: 10,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-01-18T10:00:00.000Z",
        color: "#24292E",
    },

    {
        id: "claude-pro",
        icon: icons.claude,
        name: "Claude",
        plan: "Pro",
        category: "AI",
        paymentMethod: "Mastercard ending in 6274",
        status: "active",
        startDate: "2025-03-08T10:00:00.000Z",
        price: 20,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-08T10:00:00.000Z",
        color: "#D97706",
    },

    {
        id: "openai-plus",
        icon: icons.openai,
        name: "OpenAI",
        plan: "Plus",
        category: "AI",
        paymentMethod: "Visa ending in 1458",
        status: "active",
        startDate: "2025-05-10T10:00:00.000Z",
        price: 20,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-05-10T10:00:00.000Z",
        color: "#10A37F",
    },

    {
        id: "canva-pro",
        icon: icons.canva,
        name: "Canva",
        plan: "Pro",
        category: "Design",
        paymentMethod: "Mastercard ending in 7862",
        status: "active",
        startDate: "2025-04-03T10:00:00.000Z",
        price: 12.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-04-03T10:00:00.000Z",
        color: "#00C4CC",
    },

    {
        id: "dropbox-plus",
        icon: icons.dropbox,
        name: "Dropbox",
        plan: "Plus",
        category: "Storage",
        paymentMethod: "Visa ending in 9021",
        status: "active",
        startDate: "2025-02-28T10:00:00.000Z",
        price: 11.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-02-28T10:00:00.000Z",
        color: "#0061FF",
    },

    {
        id: "medium-member",
        icon: icons.medium,
        name: "Medium",
        plan: "Member",
        category: "Reading",
        paymentMethod: "Visa ending in 5632",
        status: "active",
        startDate: "2025-01-05T10:00:00.000Z",
        price: 5,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-01-05T10:00:00.000Z",
        color: "#12100E",
    },

    {
        id: "spotify-family",
        icon: icons.spotify,
        name: "Spotify",
        plan: "Family",
        category: "Music",
        paymentMethod: "Visa ending in 7712",
        status: "active",
        startDate: "2025-03-11T10:00:00.000Z",
        price: 15.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-11T10:00:00.000Z",
        color: "#1DB954",
    },

    {
        id: "figma-org",
        icon: icons.figma,
        name: "Figma",
        plan: "Organization",
        category: "Design",
        paymentMethod: "Mastercard ending in 1184",
        status: "active",
        startDate: "2025-02-14T10:00:00.000Z",
        price: 45,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-02-14T10:00:00.000Z",
        color: "#F24E1E",
    },

    {
        id: "notion-team",
        icon: icons.notion,
        name: "Notion",
        plan: "Team",
        category: "Productivity",
        paymentMethod: "Visa ending in 2204",
        status: "active",
        startDate: "2025-01-29T10:00:00.000Z",
        price: 18,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-01-29T10:00:00.000Z",
        color: "#111111",
    },

    {
        id: "github-team",
        icon: icons.github,
        name: "GitHub",
        plan: "Team",
        category: "Developer Tools",
        paymentMethod: "Mastercard ending in 8731",
        status: "active",
        startDate: "2025-04-20T10:00:00.000Z",
        price: 21,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-04-20T10:00:00.000Z",
        color: "#181717",
    },

    {
        id: "canva-teams",
        icon: icons.canva,
        name: "Canva",
        plan: "Teams",
        category: "Design",
        paymentMethod: "Visa ending in 6612",
        status: "active",
        startDate: "2025-03-09T10:00:00.000Z",
        price: 29.99,
        currency: "USD",
        billing: "Monthly",
        renewalDate: "2026-03-09T10:00:00.000Z",
        color: "#00C4CC",
    },
];